#ingress-controller.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rider-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1 # 본인 서버에서 일관성 있는 엔드포인트
            pathType: Prefix
            backend:
              service:
                name: rider-server # 서비스 이름
                port:
                  number: 8080