#ingress-controller.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: waguwagu-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/riders # 본인 서버에서 일관성 있는 엔드포인트
            pathType: Prefix
            backend:
              service:
                name: waguwagu-rider-server # 서비스 이름
                port:
                  number: 8080
          - path: /api/v1/payments # 본인 서버에서 일관성 있는 엔드포인트
            pathType: Prefix
            backend:
              service:
                name: waguwagu-payment-server # 서비스 이름
                port:
                  number: 8080
          # - path: /api/v1/cart
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: cart # 서비스 이름
          #       port:
          #         number: 8080
          - path: /api/v1/reviews
            pathType: Prefix
            backend:
              service:
                name: review-server
                port:
                  number: 8080
